tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
brew "git"
brew "krb5"
brew "mysql", restart_service: true
brew "mysql-client"
brew "openssl@3"
brew "postgresql@14"
brew "pyenv"
brew "pyenv-virtualenv"
brew "pyenv-virtualenvwrapper"
brew "python@3.9"
brew "vue-cli"
